import Link from "next/link";
import { company, products } from "@/lib/product-family";
import { FamilyMotion, ProductConstellation } from "./family-motion";

function Arrow(){return <span aria-hidden="true">↗</span>;}

export function ProductFamily(){
  return <div className="product-family"><a className="family-skip" href="#main">Skip to content</a>
    <header className="family-nav family-wrap"><Link href="/" className="family-wordmark" aria-label="Tetheric Systems home"><span>T</span><div>tetheric<small>SYSTEMS</small></div></Link><nav aria-label="Main navigation"><a href="#products">Our products</a><a href="#approach">Our approach</a><Link href="/evidence">Company & evidence</Link></nav><a className="family-contact" href={`mailto:${company.email}`}>Let’s talk <Arrow/></a></header>
    <main id="main"><section className="family-hero family-wrap"><div className="family-hero-copy"><p className="family-eyebrow"><span/>THE COMPANY BEHIND WHAT’S NEXT</p><h1>Clarity inside.<br/><em>Possibility<br/>{" "}outside.</em></h1><p className="family-intro">We build software for the decisions you need to make—and the things you want to create.</p><div className="family-actions"><a className="family-button" href="#products">Meet our products <span>↓</span></a><a className="family-text-link" href="#approach">How we think <Arrow/></a></div><p className="family-company-note">Tetheric Systems Private Limited · India</p></div><ProductConstellation/></section>
    <div className="family-intent family-wrap"><span>THE TETHERIC PRODUCT FAMILY</span><p>Two focused products.<br/><strong>One belief in better ways of working.</strong></p><div><span className="seer-wordmark">seerflow</span><span className="family-family-divider">/</span><span className="foundry-wordmark">apex<span>foundry</span><i>.</i></span></div></div>
    <section id="products" className="family-products family-wrap"><div className="family-section-head" data-family-reveal><div><p className="family-eyebrow">BUILT FOR THE WORK THAT MATTERS</p><h2>A clearer business.<br/><em>A more expressive brand.</em></h2></div><p>Start with the problem in front of you. Each product has its own focus, its own workspace, and a place in the same family.</p></div>
      <article className="family-product family-product-seer"><div className="family-product-copy" data-family-reveal><div className="family-product-meta"><span>01 / DECISION INTELLIGENCE</span><span className="family-status live"><i/>{products.seerflow.status}</span></div><h3 className="seer-wordmark">seerflow</h3><h4>Less reconciling.<br/><em>More understanding.</em></h4><p>{products.seerflow.description}</p><ul><li>Follow cash from order to settlement.</li><li>Understand contribution, costs and returns.</li><li>Keep sources and missing inputs visible.</li></ul><div className="family-actions"><a className="family-button" href={products.seerflow.url} target="_blank" rel="noreferrer">Explore SeerFlow <Arrow/></a><Link className="family-text-link" href={products.seerflow.record}>Product record <Arrow/></Link></div><small>For Indian D2C teams. Decisions depend on connected records and explicit cost inputs.</small></div>
      <div className="family-product-visual seer-product-visual" aria-label="Illustrative SeerFlow operating view"><div className="family-window-bar"><span className="seer-wordmark">seerflow</span><span>THE OPERATING PICTURE</span><i>•••</i></div><div className="seer-window-body"><aside><b>YOUR BUSINESS</b><span className="active">◉ &nbsp; Overview</span><span>↳ &nbsp; Cash flow</span><span>↳ &nbsp; Settlements</span><span>↳ &nbsp; Contribution</span><span>↳ &nbsp; Returns</span><small>One source.<br/>A clearer decision.</small></aside><div className="seer-workspace"><div className="seer-workspace-heading"><span>FROM ORDERS TO UNDERSTANDING</span><h5>Follow the money.</h5><p>The parts belong to one picture.</p></div><div className="seer-source-path"><span>Orders</span><i>→</i><span>Payments</span><i>→</i><span>Settlements</span></div><div className="seer-trail"><svg viewBox="0 0 350 115" aria-hidden="true"><path className="seer-grid" d="M0 25H350M0 65H350M0 105H350"/><path className="seer-line-shadow" d="M0 92C40 92 40 72 80 72S125 89 155 63S210 67 250 35S310 54 350 15"/><path className="seer-line" d="M0 92C40 92 40 72 80 72S125 89 155 63S210 67 250 35S310 54 350 15"/></svg><span>TRACEABLE OPERATING CONTEXT</span></div><div className="seer-insight"><span>↗</span><div><b>A question worth asking.</b><p>What was sold, what settled, and what is still expected?</p></div></div></div></div><div className="family-visual-disclosure">Illustrative interface · no customer data or performance result</div></div></article>
      <article className="family-product family-product-foundry"><div className="family-product-copy" data-family-reveal><div className="family-product-meta"><span>02 / MARKETING & CREATIVE</span><span className="family-status">{products.foundry.status}</span></div><h3 className="foundry-wordmark">apex<span>foundry</span><i>.</i></h3><h4>One good thought.<br/><em>A world of creative.</em></h4><p>{products.foundry.description}</p><ul><li>Bring your brand, sources and ideas together.</li><li>Create copy, imagery and narrated drafts.</li><li>See the work. Refine it. Make the final call.</li></ul><div className="family-actions"><a className="family-button" href={products.foundry.url} target="_blank" rel="noreferrer">Explore Apex Foundry <Arrow/></a><Link className="family-text-link" href={products.foundry.record}>Pilot details <Arrow/></Link></div><small>In pilot with SeerFlow. Preparation and review; publishing and account access depend on separate configuration and permissions.</small></div>
      <div className="family-product-visual foundry-product-visual" aria-label="Illustrative Apex Foundry creative workspace"><div className="family-window-bar"><span className="foundry-wordmark">apex<span>foundry</span><i>.</i></span><span>THE CREATIVE WORKSPACE</span><i>•••</i></div><div className="foundry-window-body"><div className="foundry-mini-chat"><span>THE CLARITY SERIES / PROJECT CHAT</span><h5>What should we make next?</h5><div className="foundry-mini-prompt">A fresh way to tell our story.<br/>Start with what makes the brand useful.</div><div className="foundry-mini-answer"><b>✳</b><div><strong>Your creative lead</strong><p>Let’s bring the brand, the idea and the work into one conversation.</p><span>Brand research <i>↗</i></span><span>Creative directions <i>↗</i></span><span>Drafts for review <i>↗</i></span></div></div><div className="foundry-mini-input">Keep the thought going… <b>↑</b></div></div><div className="foundry-mini-board"><span>WORKING CANVAS</span><div className="foundry-mini-poster">MAKE<br/>ROOM FOR<br/><em>possibility.</em><i/><i/><i/><small>CREATIVE DIRECTION / 01</small></div><div className="foundry-mini-reel"><b>▶</b><span>A story in motion.<small>Narrated reel draft</small></span></div></div></div><div className="family-visual-disclosure">Illustrative workspace · drafts and agent activity shown as a concept</div></div></article>
    </section>
    <section id="approach" className="family-principles family-wrap"><div className="family-section-head" data-family-reveal><div><p className="family-eyebrow">A SHARED WAY OF THINKING</p><h2>Different products.<br/><em>The same care underneath.</em></h2></div><p>We start with real work, build around its context, and make room for human judgment.</p></div><div className="family-principle-path"><i className="family-path-fill"/></div><div className="family-principle-grid"><article data-family-reveal><span>01 / CONNECT THE CONTEXT</span><h3>The details belong together.</h3><p>A settlement means more beside an order. A creative idea means more beside its brand. The product should keep the relationship visible.</p></article><article data-family-reveal><span>02 / MAKE THE WORK VISIBLE</span><h3>Clarity earns confidence.</h3><p>Show the source, the draft and the gap. An idea is an idea; an estimate is an estimate. The interface should make that easy to understand.</p></article><article data-family-reveal><span>03 / KEEP PEOPLE IN CONTROL</span><h3>The final call stays yours.</h3><p>Useful software helps you move with judgment. Product access, data availability and approval should stay explicit.</p></article></div></section>
    <section className="family-company family-wrap" data-family-reveal><div className="family-company-mark">T<span>ONE COMPANY.<br/>THOUGHTFULLY CONNECTED.</span></div><div><p className="family-eyebrow">TETHERIC SYSTEMS PRIVATE LIMITED</p><h2>Building what comes next.<br/><em>One useful product at a time.</em></h2><p>We are the company behind SeerFlow and Apex Foundry. Our focus is software that makes complex work clearer and meaningful work easier to create.</p><div className="family-company-links"><Link href="/evidence">Company & evidence <Arrow/></Link><Link href="/methodology">How we describe our work <Arrow/></Link><Link href="/security">Security boundaries <Arrow/></Link></div></div></section>
    <section className="family-closing family-wrap" data-family-reveal><p className="family-eyebrow">LET’S MAKE SOMETHING USEFUL</p><h2>The next good idea<br/><em>starts with a conversation.</em></h2><a className="family-button" href={`mailto:${company.email}`}>Talk to Tetheric <Arrow/></a></section>
    </main><footer className="family-footer family-wrap"><div><Link href="/" className="family-wordmark"><span>T</span><div>tetheric<small>SYSTEMS</small></div></Link><p>{company.legalName}<br/>The company behind SeerFlow and Apex Foundry.</p><a href={`mailto:${company.email}`}>{company.email}</a></div><div><span>OUR PRODUCTS</span><a href={products.seerflow.url}>SeerFlow <Arrow/></a><a href={products.foundry.url}>Apex Foundry <Arrow/></a></div><div><span>THE COMPANY</span><Link href="/evidence">Evidence register</Link><Link href="/methodology">Methodology</Link><Link href="/security">Security</Link></div><div className="family-footer-note">India · 2026<br/>Product status and capability boundaries are linked in the public records.</div></footer><FamilyMotion/>
  </div>;
}
