import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {Disclosure,RecordLink,SectionHeading,Status,TrustShell} from "@/components/trust/trust-shell";
import {company,products} from "@/lib/product-family";
export const metadata:Metadata={title:"Evidence Register — Tetheric Systems",description:"Public product records, provenance and capability boundaries for Tetheric Systems Private Limited."};
const artifacts=[
 {id:'EV-001',name:'TS-MACHINE-01 scene archive',kind:'SCENE / .SCN',state:'CONCEPT',tone:'concept' as const,description:'Native 3D geometry, articulated rig, PBR material graph and camera/light scene.',boundary:'A designed scene. It does not establish a physical prototype or industrial performance.',url:'/models/tetherics-machine.scn',action:'Download the scene'},
 {id:'EV-002',name:'4K cinematic master',kind:'FILM / MP4',state:'CONCEPT',tone:'concept' as const,description:'3840 × 2160 offline Metal render. 96 frames at 24 fps.',boundary:'A concept film. Any sensor or recovery values are fictional narrative telemetry.',url:'/cinematic/tetherics-machine-4k.mp4',action:'Watch the film'},
 {id:'EV-003',name:'Asset manifest',kind:'PROVENANCE / JSON',state:'LIVE ARTIFACT',tone:'live' as const,description:'Resolution, renderer, modeling disclosure, byte size and SHA-256 provenance.',boundary:'The manifest records artifact properties. It does not validate the performance of a physical system.',url:'/cinematic/asset-manifest.json',action:'Inspect the manifest'},
 {id:'EV-004',name:'SeerFlow product record',kind:'PRODUCT / RECORD',state:'LIVE PRODUCT',tone:'live' as const,description:'Official product positioning and the distinction between a capability description and independently measured outcomes.',boundary:'First-party capability descriptions. No independently audited customer results are attached.',url:'/records/seerflow',action:'Read the product record',external:products.seerflow.url},
 {id:'EV-005',name:'Archived system brief',kind:'ARCHIVE / PDF',state:'CONCEPT ARCHIVE',tone:'concept' as const,description:'A portable, dated summary of the earlier system thesis and modeled physical-system boundary.',boundary:'Historical concept work, retained with its original scope.',url:'/briefs/tetherics-system-brief.pdf',action:'Open the system brief'},
 {id:'EV-006',name:'Apex Foundry pilot record',kind:'PRODUCT / RECORD',state:'PRIVATE PILOT',tone:'neutral' as const,description:'The creative workspace, human review, Build Studio and the implemented SeerFlow bridge, with their availability boundaries.',boundary:'Public information is separate from pilot workspace access. A built integration is not a live data transfer.',url:'/records/foundry',action:'Read the pilot record',external:products.foundry.url},
];
export default function EvidencePage(){return <TrustShell current="/evidence" code="COMPANY / THE EVIDENCE REGISTER" title={<>Nothing without<br/>a <em>trail.</em></>} summary="A place to inspect the work. Follow the source, understand its state, and see exactly what each artifact establishes." accent="coral" chapters={[{id:'products',label:'Product records'},{id:'ledger',label:'Evidence ledger'},{id:'states',label:'Read the states'},{id:'company',label:'Company disclosure'}]} visual={<div className="evidence-hero-art"><Image src="/cinematic/tetherics-machine-poster-4k.jpg" fill sizes="(max-width: 760px) 100vw, 50vw" alt="The archived Tetherics concept machine, rendered as a cinematic scene" priority/><div><span>ARCHIVE / TS-MACHINE-01</span><strong>A scene you<br/>can inspect.</strong><Status tone="concept">CONCEPT VISUALIZATION</Status></div><a href="/cinematic/tetherics-machine-4k.mp4" aria-label="Watch the archived concept film">↗</a></div>}>
 <section id="products" className="trust-section"><SectionHeading number="01" label="THE WORK TODAY" title={<>Two products.<br/>Different states.</>}/><div className="record-product-pair"><Link href="/records/seerflow" className="record-product-link seerflow-product" data-record-reveal><div className="evidence-product-glyph"><span>Orders</span><span>Costs</span><span>Cash</span><i>SF</i></div><Status tone="live">LIVE PRODUCT</Status><h3>SeerFlow <b>↗</b></h3><p>Connected decision intelligence for Indian D2C. Read the capability record and its source boundaries.</p></Link><Link href="/records/foundry" className="record-product-link foundry-product" data-record-reveal><div className="evidence-product-glyph"><span>Brand</span><span>Creative</span><span>Code</span><i>AF</i></div><Status>PRIVATE PILOT</Status><h3>Apex Foundry <b>↗</b></h3><p>Brand research, creative work and buildable ideas. Explore what is implemented in the pilot.</p></Link></div></section>
 <section id="ledger" className="trust-section"><SectionHeading number="02" label="INSPECTABLE ARTIFACTS" title="Open the evidence." description="Each record carries a source and a boundary. Expand an entry to see what the artifact proves—and where that proof stops."/><div className="evidence-ledger">{artifacts.map(item=><details key={item.id} data-record-reveal><summary><span>{item.id}</span><div><small>{item.kind}</small><h3>{item.name}</h3></div><Status tone={item.tone}>{item.state}</Status><b>+</b></summary><div className="evidence-entry"><p>{item.description}</p><div><span>THE BOUNDARY</span><p>{item.boundary}</p></div><RecordLink href={item.url} download={item.id==='EV-001'||undefined}>{item.action}</RecordLink>{item.external&&<RecordLink href={item.external} external>Official product information</RecordLink>}</div></details>)}</div></section>
 <section id="states" className="trust-section"><SectionHeading number="03" label="A SHARED VOCABULARY" title="A state is part of the claim."/><div className="evidence-states">{[{name:'Live',detail:'A working artifact or process you can inspect at its linked source.',mark:'↗'},{name:'Pilot',detail:'Running in a constrained setting, with a named scope and evidence.',mark:'◉'},{name:'Prototype',detail:'A testable implementation. No production or deployment claim.',mark:'⌘'},{name:'Simulation',detail:'Modeled outputs, explicitly distinct from real-world performance.',mark:'≈'},{name:'Concept',detail:'Visual intent. It does not establish a physical system or capability.',mark:'✳'},{name:'Not disclosed',detail:'No public evidence. Missing facts stay visible as missing.',mark:'—'}].map(item=><article key={item.name}><span>{item.mark}</span><div><h3>{item.name}</h3><p>{item.detail}</p></div></article>)}</div></section>
 <section id="company" className="trust-section"><SectionHeading number="04" label="ORGANIZATION DISCLOSURE" title="Known. Unknown. Not implied."/><div className="record-company-stamp"><span>T</span><div><small>THE LEGAL ENTITY</small><h3>{company.legalName}</h3><p>India · tethericsystems.com</p></div></div><div className="trust-disclosures"><Disclosure label="Product ownership" value="SeerFlow and Apex Foundry are products of Tetheric Systems Private Limited." status={<Status tone="live">DISCLOSED</Status>}/><Disclosure label="Registration documents" value="Registration documents are not published on this site." status={<Status tone="limited">NOT PUBLISHED HERE</Status>}/><Disclosure label="Leadership identities" value="No named leadership profile has been published on this site." status={<Status tone="limited">NOT DISCLOSED</Status>}/><Disclosure label="Customer outcomes" value="This company site does not assert independently verified customer performance or financial results." status={<Status tone="limited">NOT ASSERTED HERE</Status>}/><Disclosure label="Product illustrations" value="Authored interface concepts contain no customer data or measured performance results." status={<Status tone="concept">ILLUSTRATION</Status>}/><Disclosure label="General contact" value={company.email} status={<Status>CONTACT</Status>}/></div></section>
 </TrustShell>;}
