import type { Metadata } from "next";
import { Disclosure, Status, TrustShell } from "@/components/trust/trust-shell";
import { company, products } from "@/lib/product-family";

export const metadata: Metadata = { title: "Apex Foundry — Pilot Record | Tetheric Systems", description: "Apex Foundry is a creative-workspace pilot from Tetheric Systems Private Limited, bringing brand research, ideas and reviewable marketing drafts together." };

export default function FoundryRecordPage(){
  return <TrustShell code="TS/SYS-002 · PRIVATE PILOT RECORD" title="Apex Foundry." summary="A creative workspace for the idea, the team and the work. A product of Tetheric Systems Private Limited, currently in a private pilot with SeerFlow.">
    <section className="trust-section"><span className="trust-kicker">PRODUCT IDENTITY / APEX FOUNDRY</span><h2>From a brand to the next good idea.</h2><p>Apex Foundry brings brand research, source context and a team of AI specialists into a project conversation. Users can inspect activity summaries, review the resulting copy and artwork, and refine the work before deciding what happens next.</p><p><a href={products.foundry.url} target="_blank" rel="noreferrer">OPEN APEX FOUNDRY PRODUCT INFORMATION ↗</a></p>
    <div className="trust-disclosures"><Disclosure label="Owned by" value={company.legalName} status={<Status tone="live">COMPANY</Status>}/><Disclosure label="Product status" value="Private pilot with SeerFlow; workspace access is separate from this public information site." status={<Status>PRIVATE PILOT</Status>}/><Disclosure label="Product information" value={products.foundry.url} status={<Status tone="live">PUBLIC</Status>}/><Disclosure label="Record updated" value="20 September 2026" status={<Status>DATED</Status>}/></div></section>
    <section className="trust-section"><span className="trust-kicker">CURRENT PILOT SCOPE</span><h2>The context and the creative, together.</h2><div className="trust-grid">
      <article className="trust-card"><span>01 / BRAND CONTEXT</span><h3>Start with the brand</h3><p>Research public brand sources and collect identity references, colors, logos and useful facts for the project. Users review gaps and collected evidence.</p></article>
      <article className="trust-card"><span>02 / PROJECT CONVERSATION</span><h3>Work with your team</h3><p>Direct a project in a shared chat, follow agent activity summaries and inspect drafts. Activity summaries are not a disclosure of private model reasoning.</p></article>
      <article className="trust-card"><span>03 / CREATIVE DRAFTS</span><h3>Make the work visible</h3><p>Create copy, images and narrated video drafts, then review and revise. A narrated motion draft is distinct from a provider-rendered talking avatar.</p></article>
      <article className="trust-card"><span>04 / REUSABLE TEMPLATES</span><h3>Keep useful work</h3><p>Prepare reusable brand email templates and previews within a project. Template preparation does not send email or establish a mailing list.</p></article>
      <article className="trust-card"><span>05 / ACCOUNT CONNECTIONS</span><h3>Choose the destination</h3><p>Configured OAuth flows let users grant access and select supported accounts. Availability depends on provider permissions, review status and account eligibility.</p></article>
      <article className="trust-card"><span>06 / REVIEW & PLANNING</span><h3>Keep the final call</h3><p>Review assets, collect feedback and prepare a calendar or advertising proposal. Preparing a plan does not itself publish content or activate advertising spend.</p></article>
    </div></section>
    <section className="trust-section"><span className="trust-kicker">ACCESS & DATA</span><h2>Know the scope before connecting.</h2><div className="trust-callout"><strong>PILOT BOUNDARIES</strong><p>This record does not claim universal social-platform access, approved public publishing, email delivery, live ad campaigns or production availability of every planned integration. AI services process supported generation requests as described in the product privacy policy. Generated output still needs human review.</p></div><p><a href={`${products.foundry.url}/privacy.html`}>Privacy policy ↗</a> · <a href={`${products.foundry.url}/deletion.html`}>Data deletion ↗</a> · <a href={`${products.foundry.url}/terms.html`}>Pilot terms ↗</a></p><p>For pilot access or product questions, contact <a href={`mailto:${company.email}`}>{company.email}</a>.</p></section>
  </TrustShell>;
}
